ARG KBN_VERSION=please_set_kbn_version_arg

FROM docker.elastic.co/kibana/kibana:${KBN_VERSION}

ARG KBN_VERSION=please_set_kbn_version_arg
ARG ROR_VERSION=please_set_ror_version_arg
ARG ROR_LICENSE_EDITION=please_set_ror_license_edition_arg

COPY conf/kbn-02/ror-oldplatform-kibana.yml /usr/share/kibana/config/ror-oldplatform-kibana.yml
COPY conf/kbn-02/enterprise-ror-newplatform-kibana.yml /usr/share/kibana/config/enterprise-ror-newplatform-kibana.yml
COPY conf/kbn-02/pro-ror-newplatform-kibana.yml /usr/share/kibana/config/pro-ror-newplatform-kibana.yml
COPY conf/kbn-02/free-ror-newplatform-kibana.yml /usr/share/kibana/config/free-ror-newplatform-kibana.yml
COPY conf/kbn-02/kibana.crt /usr/share/kibana/config/kibana.crt
COPY conf/kbn-02/kibana.key /usr/share/kibana/config/kibana.key
COPY images/kbn-02/install-ror-kbn-using-api.sh /tmp/install-ror.sh

USER root

RUN /tmp/install-ror.sh && \
    chown -R kibana:kibana /usr/share/kibana/config

USER kibana
