apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: ${ES_VERSION}
  image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
  nodeSets:
    - name: default
      count: 2
      config:
        node.store.allow_mmap: false
