apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: ${KBN_VERSION}
  image: docker.elastic.co/kibana/kibana:${KBN_VERSION}
  count: 2
  elasticsearchRef:
    name: quickstart