kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30010
    hostPort: 9200
  - containerPort: 30011
    hostPort: 5601
  - containerPort: 30012
    hostPort: 8888
- role: worker
- role: worker
