services:

  es-xpack:
    build:
      context: .
      dockerfile: images/es/Dockerfile
      args:
        ES_VERSION: $ES_VERSION
    ports:
      - "29200:9200"
      - "29300:9300"
      - "5005:5000"
    environment:
      - cluster.name=xpack-es-cluster
      - node.name=es-xpack-single
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000"
      - ES_VERSION=$ES_VERSION
    healthcheck:
      test: [ "CMD", "curl", "-fk", "-u", "elastic:elastic", "http://localhost:9200/_security/user/kibana_system/_password", "-XPOST", "-H", "Content-Type: application/json", "-d", "{\"password\": \"elastic\"}" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    networks:
      - es-xpack-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kbn-xpack:
    build:
      context: .
      dockerfile: images/kbn/Dockerfile
      args:
        KBN_VERSION: $KBN_VERSION
    depends_on:
      es-xpack:
        condition: service_healthy
    ports:
      - "25601:5601"
    environment:
      ES_API_URL: http://es-xpack:9200
    networks:
      - es-xpack-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.14.3
    command: >
     apm-server -e
       -E apm-server.rum.enabled=true
       -E setup.kibana.host=kbn-xpack:5601
       -E setup.template.settings.index.number_of_replicas=0
       -E apm-server.kibana.enabled=true
       -E apm-server.kibana.host=kbn-xpack:5601
       -E output.elasticsearch.hosts=["es-xpack:9200"]
       -E output.elasticsearch.username=elastic
       -E output.elasticsearch.password=elastic
    depends_on:
     - es-xpack
     - kbn-xpack
    networks:
      - es-xpack-network

  server1:
    build:
      context: .
      dockerfile: images/ubuntu/Dockerfile
    command: node /example-app/app.js
    expose: 
     - 3000
    networks:
      - es-xpack-network
  
networks:
  es-xpack-network:
    driver: bridge
