ARG KBN_VERSION=please_set_kbn_version_arg

FROM docker.elastic.co/kibana/kibana:${KBN_VERSION}

ARG KBN_VERSION=please_set_kbn_version_arg
ARG ROR_FILE=please_set_ror_file_path

COPY kibana/conf/ror-newplatform-kibana.yml /usr/share/kibana/config/ror-newplatform-kibana.yml
COPY kibana/images/install-ror-kbn-using-file.sh /tmp/install-ror.sh
COPY $ROR_FILE /tmp/ror.zip

USER root

RUN /tmp/install-ror.sh && \
    chown -R kibana:kibana /usr/share/kibana/config

USER kibana
