version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://kc.localhost:8080
    volumes:
      - ./conf/keycloak/ror-realm.json:/opt/keycloak/data/import/ror-realm.json:ro
    command: ["start-dev", "--import-realm", "--hostname=kc.localhost", "--http-enabled=true", "--http-port=8080"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fksS --connect-timeout 3 --max-time 5 --retry 5 --retry-connrefused http://127.0.0.1:8080/realms/ror/.well-known/openid-configuration >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 40s
    networks:
      es-ror-network:
        aliases:
          - kc.localhost

  # when included, ensure kbn-ror waits for keycloak
  kbn-ror:
    depends_on:
      keycloak:
        condition: service_healthy

networks:
  es-ror-network:
    external: false
