ARG KBN_VERSION
ARG ROR_VERSION
ARG ROR_ACTIVATION_KEY

FROM docker.elastic.co/kibana/kibana:${KBN_VERSION}

ARG KBN_VERSION
ARG ROR_VERSION
ARG ROR_ACTIVATION_KEY

USER root
# RUN apt-get update && apt-get -y install curl git sudo
USER kibana

COPY images/kbn/install-ror-kbn-using-api.sh /tmp/install-ror.sh

ENV ROR_ACTIVATION_KEY=$ROR_ACTIVATION_KEY

RUN /tmp/install-ror.sh

USER root
RUN chown -R kibana:kibana /usr/share/kibana/config

USER kibana
COPY conf/kibana.yml /usr/share/kibana/config/kibana.yml
