ARG KBN_VERSION=please_set_kbn_version_arg

FROM docker.elastic.co/kibana/kibana:${KBN_VERSION}

ARG KBN_VERSION=please_set_kbn_version_arg
ARG ROR_VERSION=please_set_ror_version_arg

COPY conf/kbn/ror-newplatform-kibana.yml /usr/share/kibana/config/ror-newplatform-kibana.yml
COPY conf/kbn/ror-oldplatform-kibana.yml /usr/share/kibana/config/ror-oldplatform-kibana.yml
COPY conf/kbn/kibana.crt /usr/share/kibana/config/kibana.crt
COPY conf/kbn/kibana.key /usr/share/kibana/config/kibana.key
COPY images/kbn/install-ror-kbn-using-api.sh /tmp/install-ror.sh

USER root

RUN /tmp/install-ror.sh && \
    chown -R kibana:kibana /usr/share/kibana/config

USER kibana
