services:

  es-ror:
    container_name: es-ror
    env_file: ".env"
    build:
      context: ../ror-demo-cluster
      dockerfile: images/es/Dockerfile-use-ror-binaries-from-api
      args:
        ES_VERSION: ${ES_VERSION:-9.0.1}
        ROR_VERSION: ${ROR_ES_VERSION:-1.64.1}
    ports:
      - "19200:9200"
      - "19300:9300"
      - "5000:5000"
    environment:
      - cluster.name=ror-es-cluster
      - node.name=es-ror-single
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000"
      - ES_VERSION=${ES_VERSION:-9.0.1}
    healthcheck:
      test: [ "CMD", "curl", "-fk", "-u", "admin:admin", "https://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kbn-ror:
    container_name: kbn-ror
    env_file: ".env"
    build:
      context: ..
      dockerfile: coolify-demo/Dockerfile-KBN-noSSL
      args:
        KBN_VERSION: ${KBN_VERSION:-9.0.1}
        ROR_VERSION: ${ROR_KBN_VERSION:-1.64.1}
    depends_on:
      es-ror:
        condition: service_healthy
    ports:
      - "15601:5601"
    environment:
      ELASTICSEARCH_HOSTS: https://es-ror:9200
      ROR_ACTIVATION_KEY: $ROR_ACTIVATION_KEY
    healthcheck:
      test: [ "CMD", "curl", "-fk", "-u", "admin:admin", "http://localhost:5601/api/features" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    ulimits:
      memlock:
        soft: -1
        hard: -1

  initializer:
    container_name: initializer
    build:
      context: ../ror-demo-cluster
      dockerfile: images/cluster-initializer/Dockerfile
    depends_on:
      es-ror:
        condition: service_healthy
      kbn-ror:
        condition: service_healthy
    environment:
      ELASTICSEARCH_ADDRESS: https://es-ror:9200
      ELASTICSEARCH_USER: kibana
      ELASTICSEARCH_PASSWORD: kibana
    healthcheck:
      test: "test -f /tmp/init_done || exit 1"
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    volumes:
      - ../ror-demo-cluster/init-scripts:/scripts:ro
