ARG ES_VERSION=please_set_es_version_arg

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

ARG ES_VERSION=please_set_es_version_arg
ARG ROR_FILE=please_set_ror_file_path

COPY conf/es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY conf/es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY conf/es/log4j2.properties /usr/share/elasticsearch/config/log4j2.properties
COPY conf/es/ror-keystore.jks /usr/share/elasticsearch/config/ror-keystore.jks
COPY conf/es/elastic-certificates.p12 /usr/share/elasticsearch/config/elastic-certificates.p12
COPY images/es/install-ror-es-using-file.sh /tmp/install-ror.sh
COPY $ROR_FILE /tmp/ror.zip

RUN echo "" | /usr/share/elasticsearch/bin/elasticsearch-keystore create &&\
    echo 'elastic' | /usr/share/elasticsearch/bin/elasticsearch-keystore add --stdin bootstrap.password -f  &&\
    printf 'readonlyrest' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password &&\
    printf 'readonlyrest' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.truststore.secure_password &&\
    printf 'readonlyrest' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password &&\
    printf 'readonlyrest' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password

USER root
RUN /tmp/install-ror.sh

USER elasticsearch