ARG ES_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

ARG ES_VERSION
ARG ROR_FILE

COPY images/es/install-ror-es-using-file.sh /tmp/install-ror.sh
COPY $ROR_FILE /tmp/ror.zip

USER root
RUN /tmp/install-ror.sh

USER elasticsearch
COPY conf/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY conf/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY conf/log4j2.properties /usr/share/elasticsearch/config/log4j2.properties
