ARG ES_VERSION=please_set_es_version_arg

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

ARG ES_VERSION=please_set_es_version_arg
ARG ROR_VERSION=please_set_ror_version_arg

COPY conf/es/readonlyrest.yml /usr/share/elasticsearch/config/readonlyrest.yml
COPY conf/es/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY conf/es/log4j2.properties /usr/share/elasticsearch/config/log4j2.properties
COPY conf/es/ror-keystore.jks /usr/share/elasticsearch/config/ror-keystore.jks
COPY images/es/install-ror-es-using-api.sh /tmp/install-ror.sh

USER root
RUN /tmp/install-ror.sh

USER elasticsearch